export const projectsPT = [
  {
    title: "Milk Supply: Landing Page Design",
    tags: [
      "User Research",
      "Wireframing",
      "Journey Mapping",
      "User Personas",
      "Prototyping",
      "UI Design",
      "UX Design",
      "Responsive Design",
      "Interaction Design",
    ],
    description:
      "Landing page criada para apresentar o produto Milk Supply com foco em clareza, usabilidade e conversão, traduzindo um contexto técnico em uma experiência simples e orientada à decisão.",
    resultsTitle: "Resultados e foco de valor",
    results: [
      "Clareza na proposta de valor para novos usuários",
      "Redução de fricção no primeiro contato com o produto",
      "Hierarquia visual orientada à conversão",
      "Experiência responsiva e consistente entre dispositivos",
      "Base visual preparada para evolução do produto",
    ],
    buttonLabel: "Ver apresentação do projeto",
    image: "/images/milk-supply.png",
    video: "https://www.loom.com/embed/96d7c6cce3644482a4f68ac8c8aa2ec0",
  },

  {
    title: "Blog Project — Real Estate Website",
    tags: [
      "UX Research",
      "Information Architecture",
      "UI Design",
      "Content Strategy",
      "Responsive Design",
      "Interaction Design",
      "User Flows",
      "SaaS / Marketplace Experience",
    ],
    description:
      "Projeto de blog para site imobiliário com foco em arquitetura da informação, navegação eficiente e organização de grandes volumes de conteúdo, melhorando descoberta e engajamento.",
    resultsTitle: "Resultados e foco de valor",
    results: [
      "Navegação simplificada para grandes volumes de conteúdo",
      "Melhor descoberta de informações",
      "Redução da carga cognitiva durante a leitura",
      "Experiência consistente entre desktop e mobile",
      "Estrutura escalável para crescimento do conteúdo",
    ],
    buttonLabel: "Ver apresentação do projeto",
    image: "/images/blog-realestate.png",
    video: "https://www.loom.com/embed/7a332bf1954a48f1af9773db0e449cf5",
  },

  {
    title: "Redesign do site institucional — Sigasoft",
    tags: [
      "Product Design",
      "UX/UI Design",
      "B2B SaaS",
      "Information Architecture",
      "Design System",
      "Responsive Design",
      "SEO",
      "Conversion Optimization",
    ],
    description:
      "Redesign completo do site institucional com foco em clareza da proposta de valor, melhoria da hierarquia visual e alinhamento entre objetivos de negócio e experiência do usuário.",
    resultsTitle: "Resultados e foco de valor",
    results: [
      "Clareza na comunicação da proposta de valor",
      "Redução da carga cognitiva na navegação",
      "Experiência consistente entre site e produto",
      "Base escalável para marketing e evolução do produto",
      "Fortalecimento da percepção e posicionamento da marca",
    ],
    buttonLabel: "Ver apresentação do projeto",
    image: "/images/sigasoft-redesign.png",
    video: "https://www.loom.com/embed/77e8d747346743e1ba6c70cfbf6b4b46",
  },
  {
    title: "Imóveis Cerutti – Website Imobiliário",
    tags: [
        "Product Design",
        "Responsive Design",
        "Usability & Navigation",
        "Information Architecture",
        "Search Interface",
        "Mobile Experience",
        "Conversion Optimization",
        "Real Estate Experience",
    ],
    description:
      "Website imobiliário desenvolvido para a Imóveis Cerutti com foco em navegação clara, busca eficiente e experiência intuitiva para usuários encontrarem imóveis.",
    resultsTitle: "Resultados e foco de valor",
    results: [
        "Estrutura de navegação clara para descoberta rápida de imóveis",
        "Busca eficiente com filtros que facilitam a tomada de decisão",
        "Layout responsivo otimizado para desktop e mobile",
        "Interface orientada à conversão com chamadas de contato evidentes",
        "Arquitetura de informação que acompanha a jornada do usuário",
    ],
    buttonLabel: "Ver website ao vivo",
    image: "/images/imoveis-cerutti.png",
    video: "https://www.loom.com/embed/0be74fd553c047fb922fac041849dc08",
  },
  {
    title: "StockAI – Investment Intelligence Platform",
    tags: [
      "Product Design",
      "UX Strategy",
      "AI-Driven Insights",
      "Data Visualization",
      "Fintech",
      "Dashboard Design",
      "Information Architecture",
      "Decision Support",
    ],
    description:
      "Aplicação conceitual desenvolvida como challenge para uma vaga de Senior Product Designer. O projeto explora o uso de IA para apoiar decisões de investimento por meio de visualização clara de dados financeiros e insights acionáveis.",
    resultsTitle: "Resultados e foco de valor",
    results: [
      "Redução da complexidade cognitiva na leitura de dados financeiros",
      "Priorização de insights relevantes gerados por IA para tomada de decisão",
      "Interface que transmite confiança e credibilidade em um contexto sensível",
      "Arquitetura escalável para evolução de ativos, alertas e modelos de IA",
      "Alinhamento entre valor para o usuário e engajamento do negócio",
    ],
    buttonLabel: "Ver projeto no Figma",
    image: "/images/stockai.png",
    video: "https://www.figma.com/embed?embed_host=share&url=https://www.figma.com/design/HJzlY3FVTwlFtJbAigB5gi/Challenge-StockAI---Cristhofer-Pastorio",
  },
];

export default projectsPT;
